version: "3.9"
services:
  db:
    image: diamol/postgres:11.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-net
    volumes:
      - ${PGDATA}:/docker-entrypoint-initdb.d

  todo-web:
    image: diamol/ch06-todo-list:v2
    ports:
      - "8089:80"
    depends_on:
      - db
    networks:
      - app-net
    volumes:
      - ${PGDATA}:/docker-entrypoint-initdb.d
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json

networks:
  app-net:

secrets:
  postgres-connection:
    file: ./config/secrets.json